apiVersion: v1
kind: Namespace
metadata:
  name: kuboco
  labels:
    kubernetes.io/metadata.name: kuboco
---
apiVersion: v1
kind: Namespace
metadata:
  name: kuboco-containers
  labels:
    kubernetes.io/metadata.name: kuboco-containers
